# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "CSEP524: Parallel Computation"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Parallel programming course from University of Washington's Department of Computer Science and Engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://homes.cs.washington.edu/~nelson/csep524" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# deploy info
base: '/~nelson/csep524'

# Build settings
markdown: kramdown

# exclude these files
exclude: [README.md, Makefile]

